name: Argo-CD-sync
on:
  push:
  # workflow_dispatch:
    inputs:
      environment:
        description: Environment to sync argocd application
        required: true
        default: bastion
        type: choice
        options: [bastion, build, dev, qa]

jobs:
  Argo-job-sync:
    if: ${{ inputs.environment }} == 'bastion'
    runs-on: ['bastion']
    env:
      ARGO_USER: admin  
      ARGO_PASS: unified2021
   
    steps:
      - name: setting the argocd connection 
        run: |
          echo "WORKER_NODE_IP=$(kubectl get nodes | grep -v controlplane | awk '{print $1}' | tail -1)" >> $GITHUB_ENV
          echo "ARGOCD_PORT=$(kubectl -n argocd get svc argocd-server -o jsonpath='{.spec.ports[].nodePort}')" >> $GITHUB_ENV
          echo "connection string: ${{env.WORKER_NODE_IP}}:${{env.ARGOCD_PORT}}"

      - name: argocd login
        run: argocd login  ${{env.WORKER_NODE_IP}}:${{env.ARGOCD_PORT}} --username ${{env.ARGO_USER}} --password ${{env.ARGO_PASS}} --insecure
     
      - name: argocd app sync 
        run: |
          ARGOCD_APPS=$(argocd app list | awk '{print $1}' | grep -v 'NAME\|root') 
          for argo_app in $ARGOCD_APPS; do
            argocd app set $argo_app --sync-policy automated >/dev/null 2>&1
          done