name: learn-github-acctions
on:
  push:
permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: demo step-1
        run: |
          echo "Execution: demo step-1"
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::687669071903:role/learn-github-actions
          role-duration-seconds: 900 # the ttl of the session, in seconds.
          aws-region: us-east-1 # use your region here.
      - name: check the S3 bucket list 
        run: aws s3 ls
      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: make terraform cli
        uses: hashicorp/setup-terraform@v1

      - name: run terraform fmt
        run: terraform fmt -check

      - name: run terraform init
        run: terraform init

      - name: run terraform plan 
        run: terraform plan -no-color

      - name: terraform apply
        run: terraform apply -auto-approve